### ISSUE TITLE
ROS2 Humble support

### ISSUE THREAD

**Issue by Maxime-Syc** [flexivrobotics/flexiv_ros2#13]
Hello,

I noticed that only Foxy is said to be supported. I am working on a stack that requires Humble and was wondering if this package supports Humble.

Thank you

**Comment by munseng-flexiv** [comment]
Hello @Maxime-Syc, 

Yes. ROS 2 Humble will be supported. It is currently in development and `flexiv_ros2` Humble package is planned to be released in Q3 this year along with the new Flexiv RDK and Flexiv robot software release.

**Comment by Maxime-Syc** [comment]
Thank you very much! I'll run the Flexiv package in a Foxy container then. I will be posting results here in case anyone has a similar question until the release of the Humble version.
