### ISSUE TITLE
[JointTrajectoryController] Will the robot jerk when using joint trajectroy controller with Moveit ?

### ISSUE THREAD

**Issue by zengxuhe** [flexivrobotics/flexiv_ros2#23]
Hi, I am new to ROS2. I am going through your hardware interface and source code of the joint trajectory controller. I notice that the default sampling frequency is 1000Hz in your code. However, `ros2_control_node` can't ensure the same sample interval due to the program calculation difference (I have output the sample time with your code, the results showed that the interval is not consistent completely). I wonder whether the inconsistent sample interval will cause jerks using your hardware interface. If jerk happens, how will you handle it? 

ROS version: Foxy
Platform: Ubuntu 20.04

**Comment by munseng-flexiv** [comment]
Hi @zengxuhe,

I'm uncertain about the inconsistent sample interval of the `ros2_control_node` you referred to, as it could vary based on individual local setups and parallel running of other ROS nodes.

The example `test_joint_trajectory_controller.launch.py` uses the joint trajectory controller, the same default controller MoveIt uses. 

You can also run the MoveIt example in RViZ to test it: (Refer to this [Tutorial](https://moveit.picknik.ai/main/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html))
`ros2 launch flexiv_bringup rizon_moveit.launch.py robot_ip:=[robot_ip] local_ip:=[local_ip]`

I have extensively tested the joint trajectory controller in MoveIt multiple times, and I can confirm that I have not observed any instances of jerky robot behavior.

For your information, the joint trajectory controller uses the position command interface in `ros2_control`, which calls the RDK API `streamJointPosition()` [[Link](https://rdk.flexiv.com/api/classflexiv_1_1_robot.html#a7140861dae2dfd218091d537d6ffce5c)] in the hardware interface to send motion commands to the robot in [real-time (RT) mode](https://rdk.flexiv.com/manual/rdk_library.html#real-time-rt-modes). In RT modes, there are always timeliness checks on the robot side whether it receives the commands in 1 kHz. If the robot does not accept joint position commands streamed at 1kHz, it will stop and return error.

**Comment by zengxuhe** [comment]
Hi @munseng-flexiv,

Thanks for your kindly response and I have seen your Moveit tutorial.

Refer to the inconsistent sample interval, I'd like to explain some more detalis to you.

It is clear that the ros2_control_node call the [update()](https://github.com/ros-controls/ros2_control/blob/e3ae24b881219ff2f1a7ab3d9d3b2c63b9d32dba/controller_manager/src/ros2_control_node.cpp#L64) function to sample and give new commands to the robots through  RDK API streamJointPosition(). At the same time, [sample process](https://github.com/ros-controls/ros2_controllers/blob/b3e615c1d1c4b0b70f71f74af31eb6732f135a02/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L183) is conducted in update() function. And, I found the sample time is accquired by node->now() interface. To figure out the sample interval, I print out the sample time of the controller and compile the controller like this:
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/84945912/dea7ea0d-8fc2-4a5b-8aca-17c8b4af18bb)

After that, I run you Moveit example in RVIZ:
**ros2 launch flexiv_bringup rizon_moveit.launch.py robot_ip:=dont-care local_ip:=dont-care use_fake_hardware:=true**

Then, I select a point randomly in RVIZ and click _plan and excuted_ . In my terminal , the smaple time is printed out like this:
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/84945912/123a6ccd-4a7f-4958-89d2-ee583d73aa30)
It is clear that the sample interval is not consistent at each loop. Some sample intervals are lower than 1ms and others are higher than 1ms (even over 5ms in some loops). Therefore, although the trajetory carried out by spline is smooth, the speed of the robot will not consistent due to the inconsistant sample interval, which may lead to jerky robot.  

Do I miss something important to handle this problem ?  Or, does the RDK API streamJointPosition() will filter the commands from ROS2 controllers?

**Comment by munseng-flexiv** [comment]
Hi @zengxuhe 

1. You should run the MoveIt example in a real Flexiv Rizon robot instead of the fake hardware. Using fake hardware will not call the `FlexivHardwareInterface` in `flexiv_hardware`.
2. I don't think the method you used to find the timestep of the joint trajectory controller is correct, because there are post-processing logics after this [code line](https://github.com/ros-controls/ros2_controllers/blob/b3e615c1d1c4b0b70f71f74af31eb6732f135a02/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L183), but I might be wrong. You can check the `ros2_control` [documentation](https://control.ros.org/master/doc/getting_started/getting_started.html#architecture). 
The correct way to get the publish rate is `ros2 topic hz`. [[Link](https://docs.ros.org/en/foxy/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.html#ros2-topic-hz)].
3. Like I mentioned in the previous reply: 

> In RDK RT modes, there are always timeliness checks on the robot side whether it receives the commands in 1 kHz. If the robot does not accept joint position commands streamed at 1kHz, it will stop and return error.

Are there jerky robot behaviours when you run the MoveIt RViZ example on the Flexiv Rizon robot?

**Comment by zengxuhe** [comment]
Hi @munseng-flexiv ：

I am just building my custom robot on my hobby and facing the jerky problem. Thanks for you advice, I will try something else to fix it.

**Comment by munseng-flexiv** [comment]
> Hi @munseng-flexiv ：
> 
> I am just building my custom robot on my hobby and facing the jerky problem. Thanks for you advice, I will try something else to fix it.

This repo is used for the Flexiv robots. You should ask questions on [ROS Questions](https://robotics.stackexchange.com/) or the [ros2_control](https://github.com/ros-controls).
