### ISSUE TITLE
flexiv_ros2 MoveIt example cannot run in a docker environment

### ISSUE THREAD

**Issue by AGREATAPE** [flexivrobotics/flexiv_ros2#28]
Hi，I'm trying your ros2 package; but I find that I can't run through the example "ros2 launch flexiv_bringup rizon_moveit.launch.py robot_ip:=dont-care local_ip:=dont-care use_fake_hardware:=true"  in docker environment, rviz appears normally but it can't plan or run using the plugin buttons.
Here is the error reported.
if i press the plan button:
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/37623835/4aadec1e-7224-4a26-9fb5-fcbf3da21393)
if i press the execute button:
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/37623835/0690523a-d336-4294-9af5-a6a05ab7f0cb)
in the end, the robotic arm in rviz did nothing:
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/37623835/47e3f1c4-a54f-4e64-a331-3d4971b36460)

What's even weirder is that it's normal for me to run the same example on the host instead of docker.

my docker's ros version: humble
docker image is from https://moveit.picknik.ai/humble/doc/how_to_guides/how_to_setup_docker_containers_in_ubuntu.html 

please help me!

**Comment by munseng-flexiv** [comment]
@AGREATAPE 

Hello, it appeared to be a docker issue in MoveIt rather than issue related to `flexiv_ros2`. Did you try running the MoveIt tutorial examples and have the same problem? 

For your information, I use the [ROS2 docker template](https://github.com/athackst/vscode_ros2_workspace ) to run MoveIt motion planning.

**Comment by AGREATAPE** [comment]
> Hello, it appeared to be a docker issue in MoveIt rather than issue related to `flexiv_ros2`. Did you try running the MoveIt tutorial examples and have the same problem?您好，这似乎是 MoveIt 中的 docker 问题，而不是与 `flexiv_ros2` 相关的问题。您是否尝试运行 MoveIt 教程示例并遇到同样的问题？

 Yes, I have tried the moveit tutorial, and the example program of panda works properly in docker;This is also one of the reasons that puzzles me.

> For your information, I use the [ROS2 docker template](https://github.com/athackst/vscode_ros2_workspace) to run MoveIt motion planning.供您参考，我使用 ROS2 docker 模板来运行 MoveIt 运动规划。

I'll try.Thanks

**Comment by AGREATAPE** [comment]
@munseng-flexiv 
I think I found the problem. The moveit version of the docker I use is older, which forces the speed and acceleration of the joints to be set. The default value is set in the new version of moveit.
old moveit:
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/37623835/4d73331a-0dde-4b42-bba0-5cac51807f03)
new moveit:
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/37623835/eda8df8f-dd5e-48fb-939d-70654f1cb637)
