### ISSUE TITLE
How to use moveit2 and gripper  at the same time？

### ISSUE THREAD

**Issue by AGREATAPE** [flexivrobotics/flexiv_ros2#30]
I have rizon4 and the matching gripper;
The problem I encountered was that I wanted to use moveit2 to continuously control the movement of the robotic arm. After moving to the target position,I called rdk to control the gripper, but I found that rdk could not be connected to the robotic arm at this moment.
I guess it may be because moveit2 has been occupying rdk and other threads cannot connect to the robotic arm.
Is there any way to use moveit2 and gripper at the same time？
Any suggestions or ideas? Thanks.
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=2121801951519148693 skey=@crypt_7e014cec_aa96de6c8b36e2398b80cd28154353c8 mmweb_appid=wx_webfilehelper](https://github.com/flexivrobotics/flexiv_ros2/assets/37623835/596353fd-65d4-4e74-a3f3-d0bf105d5da1)

**Comment by munseng-flexiv** [comment]
Hi @AGREATAPE,

only one RDK connection is allowed at once, so you can not use ROS2 MoveIt! and RDK commands simultaneously.

gripper control is not supported directly in the `flexiv_ros2` driver yet. To control the gripper in ROS2, you must set up the corresponding gripper ROS2 driver.

**Comment by AGREATAPE** [comment]
@munseng-flexiv 
Thank you for your prompt reply. 
I do need to use moveit and gripper at the same time. Could you answer my following questions?
1.  Is flexiv's ros2 control of the flexiv gripper already in the plan? When will it be released?
2.  Besides rdk, is there any other way to control flexiv's gripper?
3.  Is it complicated to set up the ros2 driver of the gripper? Are there any relevant examples that I can refer to?

**Comment by munseng-flexiv** [comment]
> @munseng-flexiv Thank you for your prompt reply. I do need to use moveit and gripper at the same time. Could you answer my following questions?
> 
> 1. Is flexiv's ros2 control of the flexiv gripper already in the plan? When will it be released?
> 2. Besides rdk, is there any other way to control flexiv's gripper?
> 3. Is it complicated to set up the ros2 driver of the gripper? Are there any relevant examples that I can refer to?

Hi @AGREATAPE 

If the gripper you are using is Flexiv Grav gripper, the gripper control is now only supported in RDK and Flexiv Elements. 

Gripper control in ROS 2 is still in development and is planned to be released ~in version 0.10 (in Q2 2024)~ with RDK v1.x release.

**Comment by AGREATAPE** [comment]
> If the gripper you are using is Flexiv Grav gripper, the gripper control is now only supported in RDK and Flexiv Elements.

Is it possible to directly connect the gripper to the computer to control the opening and closing without using the HESPER robot controller?

**Comment by munseng-flexiv** [comment]
> > If the gripper you are using is Flexiv Grav gripper, the gripper control is now only supported in RDK and Flexiv Elements.
> 
> Is it possible to directly connect the gripper to the computer to control the opening and closing without using the HESPER robot controller?

Hi @AGREATAPE 

Currently, we do not provide the protocol or API to control the Flexiv Grav gripper independently without connecting to the control box. So to use the gripper, it must be directly connected to the control box to control Grav.

**Comment by munseng-flexiv** [comment]
@AGREATAPE 

Update: You can control the Grav gripper without the Hesper robot controller. By connecting the gripper directly to your PC with Modbus, you can use the [Modbus RTU communication protocol](https://emodbus.github.io/modbusclient-rtu-api) to control the gripper (check the Grav documentation). To control the gripper in ROS, you can try the existing ROS Modbus RTU driver to send information to the gripper (e.g. https://github.com/openvmp/modbus_rtu).

Please check the Grav user manual for more information.

**Comment by munseng-flexiv** [comment]
Update: See https://github.com/flexivrobotics/flexiv_ros2/issues/34#issuecomment-2487387871
