### ISSUE TITLE
Gripper control interface in ROS2

### ISSUE THREAD

**Issue by TomCC7** [flexivrobotics/flexiv_ros2#34]
Hi, I would like to follow up on the discussion in #30. @munseng-flexiv said that you'll release the gripper control interface in version 0.10 but I can't find anything about that in the release. Are you still planning on that? Thanks!

**Comment by munseng-flexiv** [comment]
Hi @TomCC7 

What gripper are you using? 

If the gripper you are using is Flexiv Grav gripper and you connect the Grav gripper to the control box, the direct gripper control is now only supported in RDK and Flexiv Elements. The gripper control interface will be supported together with the Flexiv ROS2/RDK v1.x release. 

Another way is by connecting the gripper directly to your PC with Modbus, you can use the [Modbus RTU communication protocol](https://emodbus.github.io/modbusclient-rtu-api) to control the gripper (check the Grav documentation). To control the gripper in ROS, you can try the existing ROS Modbus RTU driver to send information to the gripper (e.g. https://github.com/openvmp/modbus_rtu).

If you use other grippers, you can check the corresponding ROS 2 driver.

**Comment by TomCC7** [comment]
Hi, thanks for replying! It's good to know that you are still planning on that. Currently I can control the gripper through the RDK API, so I'll just write a workaround and wait for your future release.

**Comment by artyom-boyarov** [comment]
Hi Flexiv Team! I would like to follow up on this issue, as version 1.4 has been released, but I'm still not sure how to control the gripper through ROS2. Are there any examples demonstrating how to control the GRAV gripper through the ROS2 interface? 

Also, is it now possible to move the arm and gripper through one connection to the robot   (for example #30 mentions that you can't)?

Lastly, when are you planning on adding URDF files and meshes of the gripper to the humble branch of the repo? This is quite important for us as we use MoveIt for motion planning, but if MoveIt doesn't have the gripper mesh then it generates trajectories that result in the gripper hitting the arm and table.

If you could please help with these issues I will be very grateful!

**Comment by munseng-flexiv** [comment]
> Hi Flexiv Team! I would like to follow up on this issue, as version 1.4 has been released, but I'm still not sure how to control the gripper through ROS2. Are there any examples demonstrating how to control the GRAV gripper through the ROS2 interface?
> 
> Also, is it now possible to move the arm and gripper through one connection to the robot (for example #30 mentions that you can't)?
> 
> Lastly, when are you planning on adding URDF files and meshes of the gripper to the humble branch of the repo? This is quite important for us as we use MoveIt for motion planning, but if MoveIt doesn't have the gripper mesh then it generates trajectories that result in the gripper hitting the arm and table.
> 
> If you could please help with these issues I will be very grateful!

Hi @artyom-boyarov 

Thanks for your inquiry. The public release of RCA v3.6 and RDK v1.4 was last week. The gripper control interface in ROS 2, which is compatible with RDK v1.4, is still in development. I am working on it to deliver it ~by October 2024~ with v1.5 release.

The Grav gripper URDF and meshes will be added together with the Grav gripper ROS 2 driver.

Sorry for the delay.

**Comment by artyom-boyarov** [comment]
@munseng-flexiv could you please provide me an update on when to expect the v1.5 release of the Flexiv ROS2 library?

**Comment by munseng-flexiv** [comment]
> @munseng-flexiv could you please provide me an update on when to expect the v1.5 release of the Flexiv ROS2 library?

Hi @artyom-boyarov 

Flexiv ROS 2 release plan is aligned with the Flexiv RDK release plan, as Flexiv ROS 2 is built with RDK. Flexiv ROS 2 v1.5 will be released one or two weeks after the official release of Flexiv RDK v1.5.

**Comment by munseng-flexiv** [comment]
Update: The gripper control feature (of the gripper connected to the robot) is released in v1.5. For details, please refer to the [Release Note](https://github.com/flexivrobotics/flexiv_ros2/releases/tag/humble-v1.5) and the README.
