### ISSUE TITLE
include the mtl files in `flexiv_description`

### ISSUE THREAD

**Issue by TomCC7** [flexivrobotics/flexiv_ros2#35]
Hi, when I load the .obj files in `flexiv_description` I might receive a warning complaining that the .obj file referenced a .mtl file but it can't find the file. I know that the .mtl file is only for defining materials, but it would be nice if you could also include that. Here's an example of the warning message:
```bash
Meshcat: Failed to load texture. 
install/flexiv_description/share/flexiv_description/meshes/rizon4s/visual/link7.obj references link7.mtl, 
but Meshcat could not open filename "/install/flexiv_description/share/flexiv_description/meshes/rizon4s/visual/link7.mtl
```

**Comment by willnil** [comment]
Hi @TomCC7 

you can refer to the URDF. The material is defined in the [URDF xacro file](https://github.com/flexivrobotics/flexiv_ros2/blob/humble/flexiv_description/urdf/rizon4_joints_links.xacro#L227) and https://github.com/flexivrobotics/flexiv_ros2/blob/humble/flexiv_description/urdf/flexiv_arm.materials.xacro but not using the `mtl` file.

**Comment by TomCC7** [comment]
Hi, thanks for replying, I think the problem here is that [the obj file referenced mtl file](https://github.com/flexivrobotics/flexiv_ros2/blob/humble/flexiv_description/meshes/rizon4s/visual/link0.obj#L5), which caused the parser to complain. If you don't want to work with mtl files you should also remove reference to that. I shared my modifications in #36 in case you need that. :)

**Comment by munseng-flexiv** [comment]
Hi @TomCC7 

I see the parser you used is Meshcat and not using the ROS launch file. The package works well in ROS Rviz and it does not complain any errors. If you require the mtl files you can get it in the version [v0.6.1](https://github.com/flexivrobotics/flexiv_ros2/tree/v0.6.1/flexiv_description/meshes/rizon4s/visual)

**Comment by munseng-flexiv** [comment]
MTL references are removed in the OBJ files #36
